import { neon } from "@neondatabase/serverless"

const sql = neon(process.env.DATABASE_URL!)

export async function POST() {
  try {
    console.log("[v0] Starting Sharp Median data population...")

    // Clear existing data
    await sql`TRUNCATE TABLE sharp_median_employees`
    console.log("[v0] Cleared existing data")

    // Sample employee data representing different departments, roles, and scenarios
    const employees = [
      {
        employee_id: "EMP001",
        employee_name: "Sarah Johnson",
        job_title: "Senior Software Engineer",
        department: "Engineering",
        salary_or_hourly: "Salary",
        annual_salary: 125000,
        hourly_rate: null,
        original_hire_date: "2020-03-15",
        last_hire_date: "2020-03-15",
        seniority_date: "2020-03-15",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "San Francisco, CA",
        address_work: "123 Tech Street",
        city_work: "San Francisco",
        state_work: "CA",
        postal_code_work: "94105",
        country_work: "USA",
        address_home: "456 Home Ave",
        city_home: "San Francisco",
        state_home: "CA",
        postal_code_home: "94110",
        country_home: "USA",
        region: "West",
        job_code: "ENG001",
        supervisor_name: "Mike Chen",
        supervisor_employee_number: "EMP050",
        email_address: "sarah.johnson@sharpmedian.com",
        date_of_birth: "1990-05-20",
        gender: "Female",
        ethnicity: "White",
        local_currency_code: "USD",
        remote_flag: 0,
      },
      {
        employee_id: "EMP002",
        employee_name: "Marcus Williams",
        job_title: "Marketing Manager",
        department: "Marketing",
        salary_or_hourly: "Salary",
        annual_salary: 95000,
        hourly_rate: null,
        original_hire_date: "2019-08-10",
        last_hire_date: "2019-08-10",
        seniority_date: "2019-08-10",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "New York, NY",
        address_work: "789 Marketing Blvd",
        city_work: "New York",
        state_work: "NY",
        postal_code_work: "10001",
        country_work: "USA",
        address_home: "321 Brooklyn St",
        city_home: "Brooklyn",
        state_home: "NY",
        postal_code_home: "11201",
        country_home: "USA",
        region: "East",
        job_code: "MKT001",
        supervisor_name: "Lisa Rodriguez",
        supervisor_employee_number: "EMP051",
        email_address: "marcus.williams@sharpmedian.com",
        date_of_birth: "1985-11-12",
        gender: "Male",
        ethnicity: "Black or African American",
        local_currency_code: "USD",
        remote_flag: 1,
      },
      {
        employee_id: "EMP003",
        employee_name: "Jennifer Chen",
        job_title: "HR Business Partner",
        department: "Human Resources",
        salary_or_hourly: "Salary",
        annual_salary: 88000,
        hourly_rate: null,
        original_hire_date: "2021-01-20",
        last_hire_date: "2021-01-20",
        seniority_date: "2021-01-20",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Austin, TX",
        address_work: "555 HR Plaza",
        city_work: "Austin",
        state_work: "TX",
        postal_code_work: "73301",
        country_work: "USA",
        address_home: "777 Residential Dr",
        city_home: "Austin",
        state_home: "TX",
        postal_code_home: "73302",
        country_home: "USA",
        region: "South",
        job_code: "HR001",
        supervisor_name: "David Park",
        supervisor_employee_number: "EMP052",
        email_address: "jennifer.chen@sharpmedian.com",
        date_of_birth: "1988-03-08",
        gender: "Female",
        ethnicity: "Asian",
        local_currency_code: "USD",
        remote_flag: 0,
      },
      {
        employee_id: "EMP004",
        employee_name: "Robert Thompson",
        job_title: "Sales Representative",
        department: "Sales",
        salary_or_hourly: "Salary",
        annual_salary: 75000,
        hourly_rate: null,
        original_hire_date: "2018-06-01",
        last_hire_date: "2018-06-01",
        seniority_date: "2018-06-01",
        termination_date: "2023-12-15",
        termination_type: "Voluntary",
        termination_reason: "Career advancement opportunity",
        termination_reason_code: "VOL001",
        employee_status: "Terminated",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Chicago, IL",
        address_work: "999 Sales Center",
        city_work: "Chicago",
        state_work: "IL",
        postal_code_work: "60601",
        country_work: "USA",
        address_home: "111 Home Street",
        city_home: "Chicago",
        state_home: "IL",
        postal_code_home: "60602",
        country_home: "USA",
        region: "Midwest",
        job_code: "SAL001",
        supervisor_name: "Amanda Davis",
        supervisor_employee_number: "EMP053",
        email_address: "robert.thompson@sharpmedian.com",
        date_of_birth: "1982-09-25",
        gender: "Male",
        ethnicity: "White",
        local_currency_code: "USD",
        remote_flag: 0,
      },
      {
        employee_id: "EMP005",
        employee_name: "Maria Garcia",
        job_title: "Customer Support Specialist",
        department: "Customer Success",
        salary_or_hourly: "Hourly",
        annual_salary: null,
        hourly_rate: 28.5,
        original_hire_date: "2022-04-12",
        last_hire_date: "2022-04-12",
        seniority_date: "2022-04-12",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Part-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Miami, FL",
        address_work: "222 Support Ave",
        city_work: "Miami",
        state_work: "FL",
        postal_code_work: "33101",
        country_work: "USA",
        address_home: "333 Beach Rd",
        city_home: "Miami",
        state_home: "FL",
        postal_code_home: "33102",
        country_home: "USA",
        region: "South",
        job_code: "CS001",
        supervisor_name: "Kevin Lee",
        supervisor_employee_number: "EMP054",
        email_address: "maria.garcia@sharpmedian.com",
        date_of_birth: "1995-07-14",
        gender: "Female",
        ethnicity: "Hispanic or Latino",
        local_currency_code: "USD",
        remote_flag: 1,
      },
      {
        employee_id: "EMP006",
        employee_name: "James Wilson",
        job_title: "Finance Analyst",
        department: "Finance",
        salary_or_hourly: "Salary",
        annual_salary: 82000,
        hourly_rate: null,
        original_hire_date: "2020-11-03",
        last_hire_date: "2020-11-03",
        seniority_date: "2020-11-03",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Denver, CO",
        address_work: "444 Finance Tower",
        city_work: "Denver",
        state_work: "CO",
        postal_code_work: "80201",
        country_work: "USA",
        address_home: "555 Mountain View",
        city_home: "Denver",
        state_home: "CO",
        postal_code_home: "80202",
        country_home: "USA",
        region: "West",
        job_code: "FIN001",
        supervisor_name: "Rachel Kim",
        supervisor_employee_number: "EMP055",
        email_address: "james.wilson@sharpmedian.com",
        date_of_birth: "1987-12-30",
        gender: "Male",
        ethnicity: "White",
        local_currency_code: "USD",
        remote_flag: 0,
      },
      {
        employee_id: "EMP007",
        employee_name: "Ashley Brown",
        job_title: "Product Manager",
        department: "Product",
        salary_or_hourly: "Salary",
        annual_salary: 115000,
        hourly_rate: null,
        original_hire_date: "2019-02-28",
        last_hire_date: "2019-02-28",
        seniority_date: "2019-02-28",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Seattle, WA",
        address_work: "666 Product Lane",
        city_work: "Seattle",
        state_work: "WA",
        postal_code_work: "98101",
        country_work: "USA",
        address_home: "777 Tech Hill",
        city_home: "Seattle",
        state_home: "WA",
        postal_code_home: "98102",
        country_home: "USA",
        region: "West",
        job_code: "PRD001",
        supervisor_name: "Tom Anderson",
        supervisor_employee_number: "EMP056",
        email_address: "ashley.brown@sharpmedian.com",
        date_of_birth: "1991-04-18",
        gender: "Female",
        ethnicity: "Black or African American",
        local_currency_code: "USD",
        remote_flag: 1,
      },
      {
        employee_id: "EMP008",
        employee_name: "David Martinez",
        job_title: "Operations Coordinator",
        department: "Operations",
        salary_or_hourly: "Salary",
        annual_salary: 65000,
        hourly_rate: null,
        original_hire_date: "2021-09-15",
        last_hire_date: "2021-09-15",
        seniority_date: "2021-09-15",
        termination_date: "2024-01-10",
        termination_type: "Involuntary",
        termination_reason: "Performance issues",
        termination_reason_code: "INV002",
        employee_status: "Terminated",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Phoenix, AZ",
        address_work: "888 Operations Blvd",
        city_work: "Phoenix",
        state_work: "AZ",
        postal_code_work: "85001",
        country_work: "USA",
        address_home: "999 Desert Ave",
        city_home: "Phoenix",
        state_home: "AZ",
        postal_code_home: "85002",
        country_home: "USA",
        region: "West",
        job_code: "OPS001",
        supervisor_name: "Susan Taylor",
        supervisor_employee_number: "EMP057",
        email_address: "david.martinez@sharpmedian.com",
        date_of_birth: "1993-08-22",
        gender: "Male",
        ethnicity: "Hispanic or Latino",
        local_currency_code: "USD",
        remote_flag: 0,
      },
      {
        employee_id: "EMP009",
        employee_name: "Emily Davis",
        job_title: "UX Designer",
        department: "Design",
        salary_or_hourly: "Salary",
        annual_salary: 92000,
        hourly_rate: null,
        original_hire_date: "2020-07-08",
        last_hire_date: "2020-07-08",
        seniority_date: "2020-07-08",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Portland, OR",
        address_work: "111 Design Studio",
        city_work: "Portland",
        state_work: "OR",
        postal_code_work: "97201",
        country_work: "USA",
        address_home: "222 Creative St",
        city_home: "Portland",
        state_home: "OR",
        postal_code_home: "97202",
        country_home: "USA",
        region: "West",
        job_code: "DES001",
        supervisor_name: "Alex Johnson",
        supervisor_employee_number: "EMP058",
        email_address: "emily.davis@sharpmedian.com",
        date_of_birth: "1989-10-05",
        gender: "Female",
        ethnicity: "White",
        local_currency_code: "USD",
        remote_flag: 1,
      },
      {
        employee_id: "EMP010",
        employee_name: "Michael Lee",
        job_title: "Data Scientist",
        department: "Engineering",
        salary_or_hourly: "Salary",
        annual_salary: 135000,
        hourly_rate: null,
        original_hire_date: "2021-03-22",
        last_hire_date: "2021-03-22",
        seniority_date: "2021-03-22",
        termination_date: null,
        termination_type: null,
        termination_reason: null,
        termination_reason_code: null,
        employee_status: "Active",
        employee_type: "Full-time",
        organization: "Sharp Median",
        company: "Sharp Median",
        location: "Boston, MA",
        address_work: "333 Data Center",
        city_work: "Boston",
        state_work: "MA",
        postal_code_work: "02101",
        country_work: "USA",
        address_home: "444 Analytics Ave",
        city_home: "Cambridge",
        state_home: "MA",
        postal_code_home: "02139",
        country_home: "USA",
        region: "East",
        job_code: "ENG002",
        supervisor_name: "Dr. Sarah Kim",
        supervisor_employee_number: "EMP059",
        email_address: "michael.lee@sharpmedian.com",
        date_of_birth: "1986-01-15",
        gender: "Male",
        ethnicity: "Asian",
        local_currency_code: "USD",
        remote_flag: 0,
      },
    ]

    console.log(`[v0] Inserting ${employees.length} employee records...`)

    // Insert employees one by one to avoid batch issues
    let insertedCount = 0
    for (const emp of employees) {
      try {
        await sql`
          INSERT INTO sharp_median_employees (
            employee_id, employee_name, job_title, department, salary_or_hourly,
            annual_salary, hourly_rate, original_hire_date, last_hire_date, seniority_date,
            termination_date, termination_type, termination_reason, termination_reason_code,
            employee_status, employee_type, organization, company, location, address_work,
            city_work, state_work, postal_code_work, country_work, address_home, city_home,
            state_home, postal_code_home, country_home, region, job_code, supervisor_name,
            supervisor_employee_number, email_address, date_of_birth, gender, ethnicity,
            local_currency_code, remote_flag
          ) VALUES (
            ${emp.employee_id}, ${emp.employee_name}, ${emp.job_title}, ${emp.department}, ${emp.salary_or_hourly},
            ${emp.annual_salary}, ${emp.hourly_rate}, ${emp.original_hire_date}, ${emp.last_hire_date}, ${emp.seniority_date},
            ${emp.termination_date}, ${emp.termination_type}, ${emp.termination_reason}, ${emp.termination_reason_code},
            ${emp.employee_status}, ${emp.employee_type}, ${emp.organization}, ${emp.company}, ${emp.location}, ${emp.address_work},
            ${emp.city_work}, ${emp.state_work}, ${emp.postal_code_work}, ${emp.country_work}, ${emp.address_home}, ${emp.city_home},
            ${emp.state_home}, ${emp.postal_code_home}, ${emp.country_home}, ${emp.region}, ${emp.job_code}, ${emp.supervisor_name},
            ${emp.supervisor_employee_number}, ${emp.email_address}, ${emp.date_of_birth}, ${emp.gender}, ${emp.ethnicity},
            ${emp.local_currency_code}, ${emp.remote_flag}
          )
        `
        insertedCount++
        console.log(`[v0] Inserted employee ${insertedCount}: ${emp.employee_name}`)
      } catch (error) {
        console.error(`[v0] Error inserting ${emp.employee_name}:`, error)
      }
    }

    // Verify the data was inserted
    const result = await sql`SELECT COUNT(*) as count FROM sharp_median_employees`
    const totalCount = result[0].count

    console.log(`[v0] Data population complete. Total records: ${totalCount}`)

    return Response.json({
      success: true,
      message: `Successfully populated ${insertedCount} employee records`,
      totalRecords: totalCount,
    })
  } catch (error) {
    console.error("[v0] Error populating Sharp Median data:", error)
    return Response.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}
